package org.chimeramc.client.core.cosmetics;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.zip.CRC32;
import java.util.zip.Deflater;

/**
 * Minimal PNG encoder for the generated cape textures.
 *
 * <p>Bedrock cape/elytra textures are ordinary PNG files, so building them needs a PNG writer.
 * {@code android.graphics.Bitmap} would do it with less code, but it only exists on a device:
 * this runs in plain JVM unit tests, where the generated bytes can be decoded and inspected
 * without an emulator. Plain {@code Deflater}/{@code CRC32} are enough.
 *
 * <p>Output is always 8-bit RGBA (colour type 6) with filter type 0 on every scanline. That is
 * the most compatible PNG shape and the easiest to reason about; the textures are tiny, so the
 * absent per-scanline filtering costs nothing worth having.
 */
public final class PngWriter {

    private static final byte[] SIGNATURE = {
            (byte) 0x89, 'P', 'N', 'G', 0x0D, 0x0A, 0x1A, 0x0A
    };

    private PngWriter() {
    }

    /**
     * Encodes ARGB pixels into a PNG.
     *
     * @param width  image width in pixels
     * @param height image height in pixels
     * @param argb   row-major pixels, at least {@code width * height} long, 0xAARRGGBB
     */
    public static byte[] encode(int width, int height, int[] argb) {
        if (width <= 0 || height <= 0) {
            throw new IllegalArgumentException("Image size must be positive");
        }
        if (argb == null || argb.length < width * height) {
            throw new IllegalArgumentException("Pixel buffer too small for " + width + "x" + height);
        }

        byte[] raw = new byte[height * (1 + width * 4)];
        int cursor = 0;
        for (int y = 0; y < height; y++) {
            raw[cursor++] = 0;
            int rowStart = y * width;
            for (int x = 0; x < width; x++) {
                int color = argb[rowStart + x];
                raw[cursor++] = (byte) ((color >>> 16) & 0xFF);
                raw[cursor++] = (byte) ((color >>> 8) & 0xFF);
                raw[cursor++] = (byte) (color & 0xFF);
                raw[cursor++] = (byte) ((color >>> 24) & 0xFF);
            }
        }

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            out.write(SIGNATURE);

            ByteArrayOutputStream header = new ByteArrayOutputStream();
            writeInt(header, width);
            writeInt(header, height);
            header.write(8);  // bit depth
            header.write(6);  // colour type: truecolour with alpha
            header.write(0);  // compression: deflate
            header.write(0);  // filter method: adaptive
            header.write(0);  // interlace: none
            writeChunk(out, "IHDR", header.toByteArray());

            writeChunk(out, "IDAT", deflate(raw));
            writeChunk(out, "IEND", new byte[0]);
        } catch (IOException e) {
            throw new IllegalStateException("PNG encoding failed", e);
        }
        return out.toByteArray();
    }

    private static void writeInt(ByteArrayOutputStream out, int value) {
        out.write((value >>> 24) & 0xFF);
        out.write((value >>> 16) & 0xFF);
        out.write((value >>> 8) & 0xFF);
        out.write(value & 0xFF);
    }

    private static void writeChunk(ByteArrayOutputStream out, String type, byte[] data) throws IOException {
        byte[] typeBytes = type.getBytes(java.nio.charset.StandardCharsets.US_ASCII);
        writeInt(out, data.length);
        out.write(typeBytes);
        out.write(data);

        CRC32 crc = new CRC32();
        crc.update(typeBytes);
        crc.update(data);
        writeInt(out, (int) crc.getValue());
    }

    private static byte[] deflate(byte[] data) {
        Deflater deflater = new Deflater(Deflater.BEST_COMPRESSION);
        try {
            deflater.setInput(data);
            deflater.finish();
            ByteArrayOutputStream out = new ByteArrayOutputStream(data.length / 2 + 64);
            byte[] buffer = new byte[8192];
            while (!deflater.finished()) {
                int written = deflater.deflate(buffer);
                out.write(buffer, 0, written);
            }
            return out.toByteArray();
        } finally {
            deflater.end();
        }
    }
}
